---
- name: start runner
  community.docker.docker_container:
    name: eco-benchmark-runner
    image: "ghcr.io/boavizta/ecobenchmark-4-builder-efootprint:runner"
    detach: no
    user: "1000:1000"
    volumes:
      - "{{ ansible_env.HOME }}:/tmp"
    command:
      - "run"
      - "/config/scenario-{{ scenario }}.js"
      - "-e"
      - "SERVER_HOST={{ server_application_host }}:8080"
      - "--summary-export"
      - "/tmp/{{ service }}_{{ scenario }}_{{ run_id }}_k6-summary.json"
      # - "--out"
      # - "json=/tmp/{{ service }}-{{ scenario }}-{{ run_id }}-k6.json"
